
-- QNA 게시판 테이블
CREATE TABLE QNA_BOARD (
    QNA_NUM INT PRIMARY KEY AUTO_INCREMENT,
    STATUS VARCHAR(10), -- 진행 상태
    TITLE VARCHAR(50),
    USER_EMAIL VARCHAR(50) NOT NULL,
    CONTENT VARCHAR(100),
    DATE DATETIME DEFAULT SYSDATE(),
    FOREIGN KEY (USER_EMAIL) REFERENCES USER(USER_EMAIL) ON DELETE CASCADE
);


#QNA 댓글 테이블
CREATE TABLE QNA_REPLY (
    REPLY_NUM INT PRIMARY KEY AUTO_INCREMENT,
    CONTENT VARCHAR(100) NOT NULL,
    USER_EMAIL VARCHAR(50) NOT NULL,
    DATE DATETIME DEFAULT SYSDATE(),
    QNA_NUM INT NOT NULL,
    FOREIGN KEY (USER_EMAIL) REFERENCES USER(USER_EMAIL) ON DELETE CASCADE,
    FOREIGN KEY (QNA_NUM) REFERENCES QNA_BOARD(QNA_NUM) ON DELETE CASCADE
);
