
#회원테이블
CREATE TABLE REACT_MEMBER(
	MEM_ID VARCHAR(10) PRIMARY KEY
	,MEM_NAME VARCHAR(10) NOT NULL
	,MEM_PW VARCHAR(10) NOT NULL
	,MEM_TEL VARCHAR(15) UNIQUE NOT NULL
	,MEM_INTRO VARCHAR(30)
	,JOIN_DATE DATETIME DEFAULT SYSDATE()
);


INSERT INTO react_member VALUES("java","김자바","1111","010-1111-2222","안녕하세요",NOW());

SELECT * FROM react_member;