CREATE TABLE SECURITY_MEMBER(
    MEM_EMAIL VARCHAR(100) PRIMARY KEY,
    MEM_PW VARCHAR(100) NOT NULL,
    MEM_NAME VARCHAR(100) NOT NULL,
    MEM_ROLE VARCHAR(30) NOT NULL
);

SELECT * FROM SECURITY_MEMBER;
DELETE FROM SECURITY_member;
COMMIT;



