CREATE TABLE TEST (
    BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(50),
    WRITER VARCHAR(20),
    CONTENT VARCHAR(100),
    VIEWS INT DEFAULT 0,
    DATE DATETIME DEFAULT SYSDATE()
);

INSERT INTO test(BOARD_NUM,TITLE,WRITER,CONTENT,VIEWS,DATE)		
				VALUES
				(1,'프로젝트','제작','내용1',5,NOW()),
				(2,'아로젝트','파괴','내용2',2,NOW()),
				(3,'제이로젝트','창조','내용3',4,NOW());


SELECT * FROM test;
COMMIT;
ROLLBACK;

CREATE TABLE REPLY_FARMERS(
	REPLY_NUM INT PRIMARY KEY AUTO_INCREMENT,
	CONTENT VARCHAR(100) NOT NULL,
	WRITER VARCHAR(30) NOT NULL,
	DATE DATETIME DEFAULT SYSDATE(),
	BOARD_NUM INT NOT NULL REFERENCES test (BOARD_NUM)	
);

SELECT * FROM reply_farmers;
COMMIT;
ROLLBACK;
INSERT INTO REPLY_FARMERS (CONTENT, WRITER, BOARD_NUM) VALUES 
('감사요.', '농부1', 1),
('꿀팁.', '농부2', 2),
('개추요', '농부3', 1);