CREATE TABLE board_FARMERS (
    BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(50),
    WRITER VARCHAR(20),
    CONTENT VARCHAR(100),
    VIEWS INT DEFAULT 0,
    DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO board_FARMERS(BOARD_NUM,TITLE,WRITER,CONTENT,VIEWS,DATE)		
VALUES
(1,'프로젝트','제작','내용1',5,NOW()),
(2,'아로젝트','파괴','내용2',2,NOW()),
(3,'제이로젝트','창조','내용3',4,NOW());

SELECT * FROM board_FARMERS;
COMMIT;

CREATE TABLE REPLY_FARMERS (
    REPLY_NUM INT PRIMARY KEY AUTO_INCREMENT,
    CONTENT VARCHAR(100) NOT NULL,
    WRITER VARCHAR(30) NOT NULL,
    DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    BOARD_NUM INT NOT NULL,
    FOREIGN KEY (BOARD_NUM) REFERENCES board_FARMERS(BOARD_NUM) ON DELETE CASCADE
);

INSERT INTO REPLY_FARMERS (CONTENT, WRITER, BOARD_NUM) VALUES 
('감사요.', '농부1', 1),
('꿀팁.', '농부2', 2),
('개추요', '농부3', 1);

SELECT * FROM reply_farmers;
COMMIT;
ROLLBACK;

CREATE TABLE QNA_BOARD (
    QNA_NUM INT PRIMARY KEY AUTO_INCREMENT,
    STATUS VARCHAR(10), #진행상태 여부
    TITLE VARCHAR(50),
    WRITER VARCHAR(20),
    CONTENT VARCHAR(100),
    DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE QNA_REPLY (
    REPLY_NUM INT PRIMARY KEY AUTO_INCREMENT,
    CONTENT VARCHAR(100) NOT NULL,
    WRITER VARCHAR(30) NOT NULL,
    DATE DATETIME DEFAULT SYSDATE(),
    QNA_NUM INT NOT NULL  REFERENCES QNA_BOARD(QNA_NUM) ON DELETE CASCADE
);

SELECT * FROM board_farmers;
SELECT * FROM qna_reply;
SELECT * FROM reply_farmers;

DELETE FROM board_farmers WHERE BOARD_NUM = 3;

