
#쇼핑몰 회원정보 테이블
CREATE TABLE MEMBER(
#PRIMARY 중복데이터 ,NULL 못들어감
	MEM_ID VARCHAR(20) PRIMARY KEY 
	,MEE_PW VARCHAR(20) NOT NULL
	,MEM_NAME VARCHAR(10)
	,MEM_AGE INT  DEFAULT 1
	,MEM_TEL VARCHAR(15) UNIQUE #중복불가
	,JOIN_DATE DATETIME DEFAULT SYSDATE()
);

SELECT * FROM member;

INSERT INTO member (MEM_ID,MEE_PW) 
VALUES ('KIM','1111');

INSERT INTO member (MEM_ID,MEE_PW,MEM_NAME,JOIN_DATE) 
VALUES('LEE','1234','홍길동','2025-01-01');

INSERT INTO member (MEM_ID,MEE_PW,MEM_NAME,JOIN_DATE) 
VALUES('PARK','1234','홍길동','2025-01-01 10:30:50');

INSERT INTO member (MEM_ID,MEE_PW,MEM_NAME,JOIN_DATE) 
VALUES('ABC','1234','홍길동',2025010110305);

COMMIT;

SELECT * FROM MEMBER;

# 데이터 삭제
# DELECT FROM 테이블명 WHERE 조건;

DELETE FROM MEMBER WHERE MEM_NAME IS NULL;

ROLLBACK;

#데이터수정
#UPDATE 테이블명 SET 컬럼 = 바꿀값, 컬럼= 바꿀값... WHERE 조건;
UPDATE MEMBER
SET
MEM_NAME = '이순신',
MEM_AGE = 20
WHERE MEM_ID = 'ABC';
