SELECT * FROM crop_standards;

CREATE TABLE ENVIRONMENT(
   ENV_ID INT PRIMARY KEY AUTO_INCREMENT #날짜별로 얻은 데이터를 구별하기 위해 식별번호 ID를 부여 
   ,TEMPERATURE FLOAT #온도   
   ,ILLUMINANCE INT   #조도 
   ,JOIN_DATE DATETIME DEFAULT SYSDATE() #측정 날짜
);

SELECT * FROM environment;

COMMIT;

TRUNCATE TABLE environment;

ALTER TABLE ENVIRONMENT ADD COLUMN HUMIDITY FLOAT;

#토양 수분 데이터 추가
ALTER TABLE ENVIRONMENT ADD COLUMN SOIL_MOISTURE FLOAT;

ROLLBACK;

ALTER TABLE crop_standards
CHANGE COLUMN 작물 CROP VARCHAR(50),
MODIFY COLUMN temp_min FLOAT,
MODIFY COLUMN temp_max FLOAT,
MODIFY COLUMN humid_min FLOAT,
MODIFY COLUMN humid_max FLOAT,
MODIFY COLUMN soil_min FLOAT,
MODIFY COLUMN soil_max FLOAT,
MODIFY COLUMN lux_min INT,
MODIFY COLUMN lux_max INT,
MODIFY COLUMN adc_min INT,
MODIFY COLUMN adc_max INT;

#각 작물의 이미지 추가 
ALTER TABLE crop_standards
ADD COLUMN IMG_NAME VARCHAR(100);

ALTER TABLE ENVIRONMENT ADD COLUMN SOIL_MOISTURE FLOAT;

#영어 이름추가
ALTER TABLE crop_standards
ADD COLUMN ENG_NAME VARCHAR(100);

UPDATE crop_standards
SET ENG_NAME = CASE
    WHEN ID = 1 THEN 'Lettuce'
    WHEN ID = 2 THEN 'Basil'
    WHEN ID = 3 THEN 'Apple Mint'
    WHEN ID = 4 THEN 'Red Pepper'
    WHEN ID = 5 THEN 'Strawberry'
    WHEN ID = 6 THEN 'Tomato'
    WHEN ID = 7 THEN 'Spinach'  
    WHEN ID = 8 THEN 'Rosemary'  
    WHEN ID = 9 THEN 'Coralberry'  
    WHEN ID = 10 THEN 'Monstera'  
   
END
WHERE ID IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10);

ALTER TABLE crop_standards
CHANGE COLUMN id ID INT,
CHANGE COLUMN crop CROP VARCHAR(50),
CHANGE COLUMN temp_min TEMP_MIN FLOAT,
CHANGE COLUMN temp_max TEMP_MAX FLOAT,
CHANGE COLUMN humid_min HUMID_MIN FLOAT,
CHANGE COLUMN humid_max HUMID_MAX FLOAT,
CHANGE COLUMN soil_min SOIL_MIN FLOAT,
CHANGE COLUMN soil_max SOIL_MAX FLOAT,
CHANGE COLUMN lux_min LUX_MIN INT,
CHANGE COLUMN lux_max LUX_MAX INT,
CHANGE COLUMN adc_min ADC_MIN INT,
CHANGE COLUMN adc_max ADC_MAX INT;
