#적정 데이터 설명 칼럼 추가 
ALTER TABLE crop_standards ADD COLUMN DESCRIPTION TEXT;
CREATE TABLE USER(
   USER_EMAIL VARCHAR(50) PRIMARY KEY NOT NULL,
   USER_PASSWORD VARCHAR(100) NOT NULL UNIQUE,
   USER_TEL VARCHAR(50) NOT NULL UNIQUE,
   USER_ROLE VARCHAR(50) NOT NULL DEFAULT 'ROLE_FARMER',
   JOIN_DATE DATETIME NOT NULL DEFAULT SYSDATE(),
   USER_NAME VARCHAR(50) NOT NULL
); 	

CREATE TABLE PLANT_STORY(
   BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT
   ,TITLE VARCHAR(100) NOT NULL
   ,CONTENT TEXT NOT NULL
   ,READ_CNT INT DEFAULT 0
   ,REG_DATE DATETIME DEFAULT SYSDATE()
   ,USER_EMAIL VARCHAR(50) NOT NULL REFERENCES USER(USER_EMAIL)
);

#댓글 테이블
#외래 키(Foreign Key)를 DB에 설정하더라도, DTO 클래스에서는 기존처럼 평범한 필드로 작성하면 된다.
CREATE TABLE PLANT_REPLY(
  COMMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
  CONTENT TEXT NOT NULL,
  BOARD_NUM INT NOT NULL REFERENCES plant_story(BOARD_NUM) ON DELETE CASCADE,  -- 게시글 번호 (FK)
  USER_EMAIL VARCHAR(50) NOT NULL REFERENCES USER(USER_EMAIL) ON DELETE CASCADE, -- 작성자 (FK)
  REG_DATE DATETIME DEFAULT SYSDATE()  
);

#테스트용 유저 데이터
INSERT INTO USER (USER_EMAIL, USER_PASSWORD, USER_TEL, USER_ROLE, USER_NAME) VALUES
('test1@example.com', 'testpw1', '010-1111-1111', 'ROLE_FARMER', '김테스트'),
('test2@example.com', 'testpw2', '010-2222-2222', 'ROLE_FARMER', '이테스트'),
('test3@example.com', 'testpw3', '010-3333-3333', 'ROLE_FARMER', '박테스트'),
('test4@example.com', 'testpw4', '010-4444-4444', 'ROLE_FARMER', '최테스트'),
('test5@example.com', 'testpw5', '010-5555-5555', 'team4ROLE_FARMER', '정테스트');

SELECT * FROM user;
